name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build binaries
      run: cargo build --verbose
